// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package disgoslash

import mock "github.com/stretchr/testify/mock"

// MockDo is an autogenerated mock type for the Do type
type MockDo struct {
	mock.Mock
}

// Execute provides a mock function with given fields: request
func (_m *MockDo) Execute(request *InteractionRequest) (*InteractionResponse, error) {
	ret := _m.Called(request)

	var r0 *InteractionResponse
	if rf, ok := ret.Get(0).(func(*InteractionRequest) *InteractionResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*InteractionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*InteractionRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
