// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package disgoslash

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: w, r
func (_m *MockHandler) Handle(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
