// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/wafer-bw/disgoslash/models"
)

// Do is an autogenerated mock type for the Do type
type Do struct {
	mock.Mock
}

// Execute provides a mock function with given fields: request
func (_m *Do) Execute(request *models.InteractionRequest) (*models.InteractionResponse, error) {
	ret := _m.Called(request)

	var r0 *models.InteractionResponse
	if rf, ok := ret.Get(0).(func(*models.InteractionRequest) *models.InteractionResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.InteractionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.InteractionRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
