// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	slashcommands "github.com/wafer-bw/disgoslash/slashcommands"
)

// Syncer is an autogenerated mock type for the Syncer type
type Syncer struct {
	mock.Mock
}

// Run provides a mock function with given fields: guildIDs, slashCommandMap
func (_m *Syncer) Run(guildIDs []string, slashCommandMap slashcommands.Map) []error {
	ret := _m.Called(guildIDs, slashCommandMap)

	var r0 []error
	if rf, ok := ret.Get(0).(func([]string, slashcommands.Map) []error); ok {
		r0 = rf(guildIDs, slashCommandMap)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}
